# Generated by Django 2.1.7 on 2019-02-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialControl', '0003_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance_id',
            new_name='balance',
        ),
    ]
