# Generated by Django 2.1.7 on 2019-02-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialControl', '0005_auto_20190217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to='FinancialControl.Balance'),
        ),
    ]
