# Generated by Django 2.1.7 on 2019-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialControl', '0006_auto_20190217_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('slug', models.SlugField(max_length=8, unique=True)),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
