# Generated by Django 2.1.7 on 2019-02-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialControl', '0008_auto_20190217_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAmountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='negative', max_length=8),
        ),
        migrations.AlterField(
            model_name='balance',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='accountamounthistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_history', related_query_name='amount_history', to='FinancialControl.Account'),
        ),
    ]
